/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketsimulator.View;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.table.TableColumn;
import marketsimulator.Controller.InterestController;
import marketsimulator.Controller.UserController;
import Utilities.MyListingsTableModel;
import marketsimulator.Model.Property;
import Utilities.btnSeeUsersEditor;
import Utilities.btnSeeUsersRenderer;
import Utilities.PropertiesThatImInterestedTableModel;
import Utilities.btnImageEditor;
import Utilities.btnImageRenderer;
import marketsimulator.Controller.PropertyController;
import marketsimulator.Controller.setIconController;

/**
 * View for controlling your properties on sale and also
 * the properties you are interested into.
 * @author SoRa
 */
public class myHistoryView extends javax.swing.JFrame {

    /**
     * Creates new form myHistoryView
     */
    public myHistoryView() 
    {
        initComponents();
        new setIconController().setIcon(this);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMyListings = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMyInterests = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check my history");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("My Listings");

        tableMyListings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableMyListings);

        jLabel2.setText("Properties that im interested in");

        tableMyInterests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableMyInterests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void init() 
     {
       InterestController controller = new InterestController();
       PropertyController prop_controller = new PropertyController();
       
       // Lists containing my properties and my interested properties.
       ArrayList<Property> propertiesImInterestedIn = new ArrayList<Property>();
       ArrayList<Property> myListingsArray =  new ArrayList<Property>();
       propertiesImInterestedIn = controller.getMyInterests(String.valueOf(new UserController().getLoggedUser().getId()));
       myListingsArray = controller.getMyListings(String.valueOf(new UserController().getLoggedUser().getId()));
       
       // Custom table models.
       MyListingsTableModel myListingsModel = new MyListingsTableModel(myListingsArray);
       PropertiesThatImInterestedTableModel propertiesImInterestedInModel = new PropertiesThatImInterestedTableModel(propertiesImInterestedIn);
       
       //Setting the custom table models.
       tableMyListings.setModel(myListingsModel); 
       tableMyInterests.setModel(propertiesImInterestedInModel);
       
       // Getting the table column of specific columns.
       TableColumn tableSeeUsers = tableMyListings.getColumnModel().getColumn(6);
       TableColumn tableImage1 = tableMyListings.getColumnModel().getColumn(5);
       TableColumn tableImage2 = tableMyInterests.getColumnModel().getColumn(5);
       
       
       // Setting custom cell renderer for "See Users" button.
       tableSeeUsers.setCellRenderer(new btnSeeUsersRenderer());
       tableSeeUsers.setCellEditor(new btnSeeUsersEditor(new JCheckBox()));
       
       // Setting custom cell renderer for "See Image" button.
       tableImage1.setCellRenderer(new btnImageRenderer());
       tableImage1.setCellEditor(new btnImageEditor(new JCheckBox()));
       tableImage2.setCellRenderer(new btnImageRenderer());
       tableImage2.setCellEditor(new btnImageEditor(new JCheckBox()));
       
             
     }
     
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new propertyView().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableMyInterests;
    private javax.swing.JTable tableMyListings;
    // End of variables declaration//GEN-END:variables

   
}
