/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketsimulator.View;

import javax.swing.JOptionPane;
import marketsimulator.Controller.UserController;
import marketsimulator.Controller.setIconController;

/**
 *
 * @author SoRa
 */
public class personalInfoView extends javax.swing.JFrame {

    /**
     * Creates new form personalInfoView
     */
    private boolean flag;
    public personalInfoView(Boolean flag) {
        initComponents();
        this.flag = flag;
        init();
        new setIconController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPersonalInfo = new javax.swing.JTextArea();
        label_remaining_chars = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Write something about yourself so that sellers can know about you . (max 290 chars)");

        txtPersonalInfo.setColumns(20);
        txtPersonalInfo.setFont(new java.awt.Font("Ebrima", 0, 15)); // NOI18N
        txtPersonalInfo.setLineWrap(true);
        txtPersonalInfo.setRows(5);
        txtPersonalInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPersonalInfoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtPersonalInfo);

        label_remaining_chars.setText("290 Chars Remaining");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_remaining_chars)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_remaining_chars)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonalInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersonalInfoKeyTyped
        System.out.println(txtPersonalInfo.getText().length());
        int size = txtPersonalInfo.getText().length() + 1;
        
        if(size>290) evt.consume();
        else label_remaining_chars.setText(290-size + " Chars remaining");
    }//GEN-LAST:event_txtPersonalInfoKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        UserController controller = new UserController();
        
        if(flag) // if user info already added just update
        {
            if(controller.updateUserPersonalInfo(txtPersonalInfo.getText()))
            {
                JOptionPane.showMessageDialog(this,"Personal info successfully updated");
                this.dispose();
            }
            else JOptionPane.showMessageDialog(this,"Error");
        }
        else // else insert into table
        {
            if(controller.addUserPersonalInfo(txtPersonalInfo.getText()))
            {
                JOptionPane.showMessageDialog(this,"Personal info successfully saved");
                this.dispose();
            }
            else JOptionPane.showMessageDialog(this,"Error");
        }
        
       
        
    }//GEN-LAST:event_btnSaveActionPerformed
     private void init() 
     {
         // if flag is true then personal info are already set
         UserController user_controller = new UserController();
         String personal_info = user_controller.getUserPersonalInfo(String.valueOf(user_controller.getLoggedUser().getId()));
         if(flag) txtPersonalInfo.setText(personal_info);
         
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_remaining_chars;
    private javax.swing.JTextArea txtPersonalInfo;
    // End of variables declaration//GEN-END:variables

}
