/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketsimulator.View;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import marketsimulator.Controller.PropertyController;
import Utilities.PropertyOnSale_JListRenderer;
import java.io.File;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import marketsimulator.Controller.UserController;
import marketsimulator.Controller.setIconController;
import marketsimulator.Model.Property;

/**
 *
 * @author SoRa
 */
public class propertyView extends javax.swing.JFrame {

    /**
     * Creates new form propertyView
     */
    public propertyView() {
        initComponents();
        btnAddPersonalInfo.setVisible(false);
        btnEditPersonalInfo.setVisible(false);
        init();
        database_polling();
        new setIconController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        propertyList = new javax.swing.JList();
        btnAddNewProperty = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        btnEditPersonalInfo = new javax.swing.JButton();
        btnAddPersonalInfo = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Properties  on sale");
        setResizable(false);

        propertyList.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        propertyList.setToolTipText("Properties on sale");
        propertyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertyListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(propertyList);

        btnAddNewProperty.setText("Add New Property");
        btnAddNewProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPropertyActionPerformed(evt);
            }
        });

        btnHistory.setText("My History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Logged in as");

        labelUser.setForeground(new java.awt.Color(153, 153, 255));
        labelUser.setText("jLabel2");

        btnEditPersonalInfo.setText("Edit personal info");
        btnEditPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPersonalInfoActionPerformed(evt);
            }
        });

        btnAddPersonalInfo.setText("Add personal info");
        btnAddPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonalInfoActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(36, 36, 36))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddNewProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(14, 14, 14)))
                            .addComponent(btnEditPersonalInfo)
                            .addComponent(btnAddPersonalInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnLogout))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddNewProperty)
                .addGap(57, 57, 57)
                .addComponent(btnHistory)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUser)
                .addGap(31, 31, 31)
                .addComponent(btnAddPersonalInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPersonalInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPropertyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddNewPropertyView().setVisible(true);
    }//GEN-LAST:event_btnAddNewPropertyActionPerformed

    private void propertyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyListMouseClicked
        // TODO add your handling code here:
         Property prop = (Property) propertyList.getSelectedValue() ;
         new propertyDetailsView(prop).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_propertyListMouseClicked

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        this.setVisible(false);
        new myHistoryView().setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnEditPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPersonalInfoActionPerformed
//       
        new personalInfoView(true).setVisible(true);
    }//GEN-LAST:event_btnEditPersonalInfoActionPerformed

    private void btnAddPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonalInfoActionPerformed
        new personalInfoView(false).setVisible(true);
    }//GEN-LAST:event_btnAddPersonalInfoActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        File file = new File(System.getProperty("user.home")+"\\remember.ser");
        File file2 = new File(System.getProperty("user.home")+"\\user.ser");
        if(file.delete() && file2.delete())
        {
            JOptionPane.showMessageDialog(this,"Logged out");
            new mainView().setVisible(true);
            this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Error");
    }//GEN-LAST:event_btnLogoutActionPerformed

   public void init()
   {                   
       UserController user_controller = new UserController();
       //check if personal info has been saved in logged user
       if(user_controller.getLoggedUser().getPersonal_details() == null )
       {
           btnAddPersonalInfo.setVisible(true);
           btnEditPersonalInfo.setVisible(false);
       }
       else
       {
           btnAddPersonalInfo.setVisible(false);
           btnEditPersonalInfo.setVisible(true);
       }
       
       labelUser.setText(user_controller.getLoggedUser().getFirstname() + " \n " + user_controller.getLoggedUser().getLastname());
       
       PropertyController controller = new PropertyController();
       DefaultListModel model = new DefaultListModel();
       ArrayList<Property> properties = new ArrayList<Property>();
       
       properties = controller.getProperties();
       
       
       for(Property prop : properties)
       {
           model.addElement(prop);
   
       }
       propertyList.setCellRenderer(new PropertyOnSale_JListRenderer());
       propertyList.setModel(model);
       
      
   }
   
    private void database_polling() {
          Runnable r = new Runnable() {

           @Override
           public void run() {
              init();
              System.out.println("Database Polling");
           }
       };
       ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
       scheduler.scheduleAtFixedRate(r, 3, 3, TimeUnit.SECONDS);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProperty;
    private javax.swing.JButton btnAddPersonalInfo;
    private javax.swing.JButton btnEditPersonalInfo;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUser;
    private javax.swing.JList propertyList;
    // End of variables declaration//GEN-END:variables

   
}
