/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketsimulator.View;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import marketsimulator.Controller.PropertyController;
import marketsimulator.Model.JListRenderer;
import marketsimulator.Model.Property;

/**
 *
 * @author SoRa
 */
public class propertyView extends javax.swing.JFrame {

    /**
     * Creates new form propertyView
     */
    public propertyView() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        propertyList = new javax.swing.JList();
        btnAddNewProperty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        propertyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertyListMouseClicked(evt);
            }
        });
        propertyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                propertyListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(propertyList);

        btnAddNewProperty.setText("Add New Property");
        btnAddNewProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPropertyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnAddNewProperty)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnAddNewProperty)))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPropertyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddNewPropertyView().setVisible(true);
    }//GEN-LAST:event_btnAddNewPropertyActionPerformed

    private void propertyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_propertyListValueChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_propertyListValueChanged

    private void propertyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyListMouseClicked
        // TODO add your handling code here:
        int prop =  evt.getModifiers();
         JOptionPane.showMessageDialog(this,((Property)propertyList.getSelectedValue()).getName());
    }//GEN-LAST:event_propertyListMouseClicked

    /**
     * @param args the command line arguments
     */
   public void init()
   {
       PropertyController controller = new PropertyController();
       DefaultListModel model = new DefaultListModel();
       ArrayList<Property> properties = new ArrayList<Property>();
       properties = controller.getProperties();
       for(Property prop : properties)
       {
           model.addElement(prop);
   
       }
       propertyList.setCellRenderer(new JListRenderer());
       propertyList.setModel(model);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProperty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList propertyList;
    // End of variables declaration//GEN-END:variables
}
